// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIEwNSKf1l0TUdx_yDoRXeulnRHDKomI',
    appId: '1:815521595195:web:4320f1715f33055176c11e',
    messagingSenderId: '815521595195',
    projectId: 'revealingchristmission-2f35d',
    authDomain: 'revealingchristmission-2f35d.firebaseapp.com',
    storageBucket: 'revealingchristmission-2f35d.appspot.com',
    measurementId: 'G-75554FQHM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYHNXS2Yr4pGf48V-svYJpiTXVyM7eUnw',
    appId: '1:815521595195:android:5b429784e260a47776c11e',
    messagingSenderId: '815521595195',
    projectId: 'revealingchristmission-2f35d',
    storageBucket: 'revealingchristmission-2f35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJMSqMEh7W9etbAjLG56f42V2sOTlugc',
    appId: '1:815521595195:ios:e8762a5886f8ffa876c11e',
    messagingSenderId: '815521595195',
    projectId: 'revealingchristmission-2f35d',
    storageBucket: 'revealingchristmission-2f35d.appspot.com',
    iosClientId: '815521595195-pp69r0uhbkkkju4icg33qb95cjkcaqbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.revealingChristMission',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeJMSqMEh7W9etbAjLG56f42V2sOTlugc',
    appId: '1:815521595195:ios:e8762a5886f8ffa876c11e',
    messagingSenderId: '815521595195',
    projectId: 'revealingchristmission-2f35d',
    storageBucket: 'revealingchristmission-2f35d.appspot.com',
    iosClientId: '815521595195-pp69r0uhbkkkju4icg33qb95cjkcaqbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.revealingChristMission',
  );
}
